[build]
target = "thumbv8m.main-none-eabi"

[target.thumbv8m.main-none-eabi]
rustflags = [
  "-C", "link-arg=--cmse-implib",
  "-C", "link-arg=--out-implib=target/thumbv8m.main-none-eabi/release/veneers.o"
]
